package net.nawia.gsao.domain;

public class Player {
//	CREATE TABLE "players" (
//		    "id" SERIAL,
//		    "name" VARCHAR(255) NOT NULL,
//		    "account_id" INT NOT NULL,
//		    "group_id" INT NOT NULL,
//		    "sex" SMALLINT NOT NULL DEFAULT 0,
//		    "vocation" SMALLINT NOT NULL DEFAULT 0,
//		    "experience" BIGINT NOT NULL DEFAULT 0,
//		    "level" BIGINT NOT NULL DEFAULT 1,
//		    "maglevel" BIGINT NOT NULL DEFAULT 0,
//		    "health" BIGINT NOT NULL DEFAULT 100,
//		    "healthmax" BIGINT NOT NULL DEFAULT 100,
//		    "mana" BIGINT NOT NULL DEFAULT 100,
//		    "manamax" BIGINT NOT NULL DEFAULT 100,
//		    "manaspent" BIGINT NOT NULL DEFAULT 0,
//		    "soul" BIGINT NOT NULL DEFAULT 0,
//		    "direction" SMALLINT NOT NULL DEFAULT 0,
//		    "lookbody" BIGINT NOT NULL DEFAULT 10,
//		    "lookfeet" BIGINT NOT NULL DEFAULT 10,
//		    "lookhead" BIGINT NOT NULL DEFAULT 10,
//		    "looklegs" BIGINT NOT NULL DEFAULT 10,
//		    "looktype" BIGINT NOT NULL DEFAULT 136,
//		    "lookaddons" BIGINT NOT NULL DEFAULT 0,
//		    "posx" INT NOT NULL DEFAULT 0,
//		    "posy" INT NOT NULL DEFAULT 0,
//		    "posz" INT NOT NULL DEFAULT 0,
//		    "cap" INT NOT NULL DEFAULT 0,
//		    "lastlogin" BIGINT NOT NULL DEFAULT 0,
//		    "lastlogout" BIGINT NOT NULL DEFAULT 0,
//		    "lastip" BIGINT NOT NULL DEFAULT 0,
//		    "save" SMALLINT NOT NULL DEFAULT 1,
//		    "conditions" BYTEA NOT NULL,
//		    "skull_type" SMALLINT NOT NULL DEFAULT 0,
//		    "skull_time" BIGINT NOT NULL DEFAULT 0,
//		    "loss_experience" INT NOT NULL DEFAULT 100,
//		    "loss_mana" INT NOT NULL DEFAULT 100,
//		    "loss_skills" INT NOT NULL DEFAULT 100,
//		    "loss_items" INT NOT NULL DEFAULT 10,
//		    "loss_containers" INT NOT NULL DEFAULT 100
//		    "town_id" INT NOT NULL,
//		    "balance" INT NOT NULL DEFAULT 0,
//		    "stamina" INT NOT NULL DEFAULT 151200000,
//		    "online" SMALLINT NOT NULL DEFAULT 0,
//		    "rank_id" INT NOT NULL,
//		    "guildnick" VARCHAR(255) NOT NULL,
//		    PRIMARY KEY ("id"),
//		    UNIQUE ("name"),
//		    KEY ("online"),
//		    FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") ON DELETE CASCADE,
//		    FOREIGN KEY ("group_id") REFERENCES "groups" ("id")
//		);
}
